ingress:
  # Enable ingress for home assistant
  enabled: true
  spec:
    ingressClassName: "traefik"
  annotations:
    kubernetes.io/ingress.class: "traefik"
    kubernetes.io/tls-acme: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/router.tls: "true"